securedrop-client/debian/changelog, securedrop-proxy/debian/changelog
This is on top of #9 and contains the changelog updates for `securedrop-proxy 0.1.1` and `securedrop-client 0.0.2`, I built debs and they are now on apt-test-qubes.freedom.press (thanks to @emkll for pushing the packages up)
=> securedrop-proxy 0.1.1 and securedrop-client 0.0.2

scripts/build-debianpackage, securedrop-client/debian/changelog, securedrop-proxy/debian/changelog
The new build logic that came in via #9 introduced a regression, where
the venv path inside the scripts packaged in the debs was
inappropriately using a fullpath from the build environment.
Modifying the pardir to match the package name exactly resolved; it was
necessary to tweak the tar command to make sure the files land adjacent
to the debian dir as the build tooling expects.
Closes #12.
=> Resolves venv paths in python deb packages

securedrop-client/debian/changelog, securedrop-client/debian/securedrop-client.install
Requires securedrop-client 0.0.4 code from https://github.com/freedomofpress/securedrop-client/pull/141
Towards https://github.com/freedomofpress/securedrop-workstation/issues/198 : Once this and the client PR are merged, we will need to update the application list to have only SecureDrop Client in the application menu for sd-svs.
Test plan:
```
git clone https://github.com/freedomofpress/securedrop-client
git checkout 0.0.4
python3 setup.py sdist
PKG_VERSION=0.0.4 make securedrop-client
```
=> Add .desktop file shortcut for securedrop-client

securedrop-client/debian/changelog
Packages are already on apt-test-qubes.freedom.press
=> Bump securedrop-client to 0.0.5-1

Makefile, README.md, scripts/build-debianpackage, scripts/update-changelog
Fixes #19. 
Build of any of the existing package. Remember to update the path based on the location of the source tarball.
```
PKG_PATH=/home/user/code/securedrop-client/dist/securedrop-client-0.0.5.tar.gz PKG_VERSION=0.0.5 make securedrop-client
```
=> Removes dch and localwheels syncing part of build steps

scripts/build-debianpackage, securedrop-client/debian/rules, securedrop-proxy/debian/rules
Using these changes we can have reproducible builds, as we will be using the same source tarball and also the same wheels to build the final package.
Fixes #32.
Build the `securedrop-client` twice, after the first build, move the deb package to a directory called `aa` and then the second build to `bb`. After this run `diffoscope` against them.
```
mkdir aa bb
PKG_PATH=/home/user/code/securedrop-client/dist/securedrop-client-0.0.6.tar.gz PKG_VERSION=0.0.6 make securedrop-client
mv ~/debbuild/packaging/securedrop-client_0.0.6_all.deb aa/
PKG_PATH=/home/user/code/securedrop-client/dist/securedrop-client-0.0.6.tar.gz PKG_VERSION=0.0.6 make securedrop-client
mv ~/debbuild/packaging/securedrop-client_0.0.6_all.deb bb/
$ diffoscope aa/securedrop-client_0.0.6_all.deb …
```
=> Fixes #32 brings reproducible builds back

securedrop-proxy/debian/changelog
Now one can build `securedrop-proxy` `0.1.3` package.
=> Updates changelog for securedrop-proxy 0.1.3

securedrop-client/debian/changelog, securedrop-client/debian/securedrop-client.install
When trying to run the client from the debian package install, Kushal and I ran into an error where it was trying to look for a couple alembic migration files that had been deleted. We ended making the changes in this PR in order to build the 0.0.7 release of the client to get passed this error.
1. build debian package of the client with this changes to the install file
2. install
3. run and see no error about trying to find the alembic files that were removed in this PR
/cc @kushaldas @redshiftzero
=> update install file for the securedrop client

README.md
I forgot to update the release manager steps in #43, here are the text changes to reduce confusion for release managers. diagram and gif still need updating or removing, which we should do in a separate PR
=> Update release manager steps to account for pipenv removal

.circleci/config.yml, README.md, scripts/verify-sha256sum-signature
This gets us towards #8 and will help catch build breakage (e.g. c0b2e6b6d7a1de4f69b816404a1c35a2e9472a87 which fixes broken securedrop-client package builds) that is currently getting merged due to no CI.
Temporarily blocked until we release new versions of `securedrop-client` and `securedrop-proxy` (see below).
*Updated description as PR dependency has since been merged.  - @eloquence 2019-06-11*
=> Add pipeline for building Debian packages in CircleCI

securedrop-client/debian/changelog, securedrop-proxy/debian/changelog
Towards https://github.com/freedomofpress/securedrop-workstation/issues/268
Add changelog entries for the latest releases of the proxy and client. Still need to upload the packages to the test apt server.
=> changelog for sdc 0.0.8 and proxy 0.1.4

securedrop-client/debian/securedrop-client.install
Closes #53
Needed to address this because https://github.com/freedomofpress/securedrop-client/pull/427 is adding a new migration, and I don't want the nightly build to be added soon in #58 to start producing a non-working package when we merge that PR
For the lazy (this is how I tested this), the `build-securedrop-client` CI job here is handy, one can wait until the package is built in the `build-securedrop-client` job, SSH in to the circle CI box and:
0. `cd ~/debbuild/packaging`
1. `ar x <name_of_deb>`
2. `tar xvf data.tar.xz`
3. `ls usr/share/securedrop-client/alembic/versions/`
4. Confirm you see the migration, even though we didn't specify it manually
=> securedrop-client.install: use wildcard for alembic migrations

.circleci/config.yml
Closes https://github.com/freedomofpress/securedrop-client/issues/407 (see rationale for versioning scheme [here](https://github.com/freedomofpress/securedrop-client/issues/407#issuecomment-503283197))
Contains securedrop-client side changes for https://github.com/freedomofpress/securedrop-debian-packaging/issues/50
Test build [here](https://circleci.com/gh/freedomofpress/securedrop-debian-packaging/57): observe the built package is in `/home/circleci/debbuild/packaging/securedrop-client_0.0.8-dev-20190618-205506_all.deb` 
This PR also contains some DRYing up so that the securedrop-proxy version of this change will be pretty minimal (to do once https://github.com/freedomofpress/securedrop-proxy/pull/37 is merged)
=> ci: increment version and build nightly securedrop-client deb package

README.md
Changes in this repository for: https://github.com/freedomofpress/securedrop-debian-packaging/issues/48
=> release manager/maintainer doc changes needed for nightly builds

.circleci/config.yml
Closes #50 
This PR adds a nightly CI job to increment the version of securedrop-proxy and build the debian package (the CI run steps being used here were added in #58)
You can verify this works by looking at this build: https://circleci.com/gh/freedomofpress/securedrop-debian-packaging/99 and observing the built package in `/home/circleci/debbuild/packaging/securedrop-proxy_0.1.4-dev-20190625-173008_all.deb`
=> ci: increment version and build nightly securedrop-proxy deb package

securedrop-workstation-grsec/50-disable-mds-smt.cfg, securedrop-workstation-grsec/debian/changelog, securedrop-workstation-grsec/debian/control, securedrop-workstation-grsec/debian/postinst, securedrop-workstation-grsec/debian/securedrop-workstation-grsec.install
Ready for review
Updates version strings and changelog for grsec kernels for the securedrop-workstation qubes template.
Configs are in https://github.com/freedomofpress/ansible-role-grsecurity-build/pull/49
Kernels packaging (incliding this `securedrop-workstation-grsec` metapackage) are live on apt-test-qubes.freedom.press.
=> Update grsec kernels to 4.14.128

.circleci/config.yml
Closes #51
This PR makes the nightly workflow first build securedrop-proxy, then commit to master in the dev packages LFS repo, then do the same for securedrop-client.
One can observe the bot account commit packages here: https://github.com/freedomofpress/securedrop-dev-packages-lfs/commits/master
=> ci: commit workstation debs to lfs repo after nightly build

.circleci/config.yml
Adds nightly build and commits to LFS  deb packages for securedrop-export (see https://github.com/freedomofpress/securedrop-debian-packaging/pull/64 and https://github.com/freedomofpress/securedrop-debian-packaging/pull/61)
=> Add nightly builds for securedrop-export package

Makefile, securedrop-client/debian/changelog, securedrop-client/debian/securedrop-client.install
The files referenced here were added to the manifest file in the
"securedrop-client" repository, ensuring they are included in the
tarball used for creating a Debian package.
See corresponding client changes in https://github.com/freedomofpress/securedrop-client/pull/490
0. Set up build environment as per this repo's README
1. Create a source tarball using this branch of securedrop-client: https://github.com/freedomofpress/securedrop-client/pull/490
2. set PKG_VERSION: `export PKG_VERSION=0.0.8`
3. run make: `make securedrop-client`
=> Adds sd-svs mimetype handlers to securedrop-client pkg

Makefile, README.md
Updates `README.md` with instructions. 
Fixes #55
=> Updates the instruction about wheel builds and syncing

.circleci/config.yml
trying to fix #77
basically the issue here as I understand it is that we have a build error occurring at the tip of `master` due to running out of seats last month in circle ci. if you re-run the job, it'll still error (because the commit is from a time period where we had no seats... seems like not the ideal behavior but let's put that aside for now) meaning that in order to get our nightly builds running again we need to get a passing build on `master`, which is what this PR does.
=> ci: trivial commit to retrigger nightly debian package builds

securedrop-export/debian/changelog
See https://github.com/freedomofpress/securedrop-export/pull/17 for changes to securedrop-export code
=> Bump securedrop-export to 0.1.2

securedrop-workstation-config/debian/changelog, securedrop-workstation-config/debian/control, securedrop-workstation-grsec/debian/changelog, securedrop-workstation-grsec/debian/control, securedrop-workstation-grsec/debian/postinst
* Update grsec kernels to 4.14.151
* Update GRUB_DEFAULT value to 4.14.151-grsec-workstation in /etc/default/grub
=> Update SecureDrop workstation kernels to 4.14.151

scripts/update-requirements
Now we can have multiple wheels hashes into the build-requirement
script, for python3.5 and python3.7
On a Buster VM/system
This should create a build-requirements.txt with multiple hashes for sqlalchemy and MarkupSafe wheels.
=> Updates the script to add multiple wheel hashes

.circleci/config.yml, securedrop-client/debian/rules
Resolves #88
To test the same, you will have to build the package in a Debian Buster VM or container.
For the CI, I have also updated the per PR build job to build nightly client, as the last release of the securedrop-client (0.0.9) can not be built on Buster (due to wheel dependency).
I am going to update the CI for `securedrop-client` in the next PR.
=> Updates to Python 3.7 on Buster for package building for securedrop-client

.circleci/config.yml, securedrop-client/debian/rules
Reverts freedomofpress/securedrop-debian-packaging#89
=> Revert "Updates to Python 3.7 on Buster for package building for securedrop-client"

.circleci/config.yml, securedrop-proxy/debian/changelog-buster, securedrop-proxy/debian/changelog-stretch, securedrop-proxy/debian/rules, securedrop-proxy/debian/securedrop-proxy.triggers
Adds a `securedrop-proxy` build job for Python 3.7 on Buster.
To test, build the `securedrop-proxy` debian package in a Buster VM and run through test plan to make sure it is functioning as normal without regression.
=> add build job for python3.7-buster

.circleci/config.yml, securedrop-export/debian/changelog-buster, securedrop-export/debian/rules, securedrop-export/debian/securedrop-export.triggers
Closes #92 
Corresponding securedrop-export buster package in: https://github.com/freedomofpress/securedrop-dev-packages-lfs/pull/26
=> ci/build changes for securedrop-export

.circleci/config.yml
Fixes #100 
You can confirm this works via either:
- [this branch](https://github.com/freedomofpress/securedrop-debian-packaging/compare/test-changelog-step) which contains a test job that runs the failing run step, it passes CI [here](https://circleci.com/gh/freedomofpress/securedrop-debian-packaging/942)
- this succeeding "nightly" build that I ran ad hoc based on this branch so we got updated debs with the latest - https://circleci.com/gh/freedomofpress/securedrop-debian-packaging/952
=> fix nighty builds

.circleci/config.yml
Towards #95 
- Renamed stretch nightly builds to build-nightly-stretch-<package>
- Added buster nightly builds for all packages
=> Buster nightly builds for client, proxy and export

.circleci/config.yml
Adds nightly build for securedrop-log, see package built on this logic https://github.com/freedomofpress/securedrop-dev-packages-lfs/commit/6faa9b32a08110d57eec36b3f1a02e26424379c4 deployed here https://apt-test-qubes.freedom.press/pool/main/s/securedrop-log/
=> add nightly build for securedrop-log

securedrop-log/debian/changelog-buster
Adds the missing changelog entry for 0.0.3 version of `securedrop-log`
=> Adds 0.0.3 changelog entry

.circleci/config.yml, Makefile, securedrop-workstation-grsec/debian/changelog-buster, securedrop-workstation-grsec/debian/changelog-stretch, securedrop-workstation-grsec/debian/control, securedrop-workstation-grsec/debian/postinst
Towards https://github.com/freedomofpress/securedrop-workstation/issues/234
* Add makefile target to build kernel metapackage, decouple stretch and buster changelogs
* Add CI job for securedrop-workstation-grsec (both stretch and buster)
=> Provide apparmor kernel support, bump kernel to 4.14.158

securedrop-client/debian/control, securedrop-client/debian/postinst, securedrop-client/debian/securedrop-client.install
Towards https://github.com/freedomofpress/securedrop-workstation/issues/234 :
* Bump kernel image to support AppArmor (see changes in https://github.com/freedomofpress/ansible-role-grsecurity-build/pull/54)
* Logic to copy, squash and enforce AppArmor profile for securedrop-client
subset of https://github.com/freedomofpress/securedrop-workstation/pull/364 , required a vm with apparmor support:
=> AppArmor support and profile for securedrop-client

securedrop-client/debian/changelog-buster, securedrop-client/debian/postinst
Towards https://github.com/freedomofpress/securedrop-workstation/pull/364
In #116 we've introduced apparmor support but discovered, after merging 2 issues:
1. if the kernel is not running 4.14.158 or above, the postinst for the client will fail when attempting to enforce the apparmor profile, resulting in a potentially broken template
2. The debian changelog was not updated.
To immediately resolve (and not break nightlies), let's merge this ASAP and enforce the apparmor profile via /rw/config/rc.local in the securedrop-workstation salt logic as part of https://github.com/freedomofpress/securedrop-workstation/pull/364
* build securedrop-client on this branch: `PKG_VERSION=0.0.11 PKG_PATH=../securedrop-client/dist/securedrop-client-0.0.11.tar.gz make securedrop-client`
=> Update debian changelog and don't enforce apparmor profile in postinst

securedrop-workstation-svs-disp/debian/changelog-buster, securedrop-workstation-svs-disp/debian/control, securedrop-workstation-svs-disp/debian/postinst, securedrop-workstation-svs-disp/debian/securedrop-workstation-svs-disp.install
closes https://github.com/freedomofpress/securedrop-workstation/issues/384
This will ensure upstream apparmor profiles are installed and enforced. This includes profiles for:
* libreoffice
* totem
* evince
It appears that in compat level 10 (default for buster), files are not copied to /etc . Since we want to automatically squash the paxctld configuration, let's move it to `/opt` and move in place to `/etc` in postinst.
- check out this branch
- move package to sd-svs-disp-buster-template and install package in that template (`sudo apt-get -f install to resolve dependencies`)
- in sd-svs-disp, open a pdf in evince
=> Install apparmor profiles in sd-svs-disp

securedrop-export/debian/postinst
Fixes https://github.com/freedomofpress/securedrop-export/issues/37
This will ensure there are no popups to display to reduce user confusion because:
- sd-export-usb is a disposableVM, and the changes won't persist
- printer drivers are automatically installed by securedrop-export
This is the easy way to ensure no popups will be displayed, but will mean that popup messages such as https://github.com/freedomofpress/securedrop-export/blob/e4239d88dfb22cdfc03859609184ca7494045058/securedrop_export/print/actions.py#L163 will no longer work. I believe the plan of record was to get rid of them, I will open a follow-up PR to remove those in sd-export.
=> Disable notifications in sd-export VMs

LICENSE, scripts/update-changelog, securedrop-client/debian/changelog-stretch, securedrop-client/debian/control, securedrop-client/debian/copyright, securedrop-client/debian/postinst, securedrop-log/debian/copyright, securedrop-proxy/debian/changelog-buster, securedrop-proxy/debian/changelog-stretch, securedrop-proxy/debian/control, securedrop-proxy/debian/copyright, securedrop-workstation-config/debian/copyright, securedrop-workstation-grsec/debian/copyright, securedrop-workstation-grsec/debian/postinst, securedrop-workstation-svs-disp/debian/copyright, securedrop-workstation-svs-disp/debian/postinst
Closes #108 
- Standardizes maintainer information
- updated control files to ensure proper upsteam repos are used
- fixes typos in historical changelogs
- sets default `DEBFULLNAME` and `DEBEMAIL` to `SecureDrop Team <securedrop@freedom.press>`
- adds LICENCE file (copied from securedrop-client repository)
=> Update copyright and maintainer information

securedrop-client/debian/rules, securedrop-export/debian/rules, securedrop-proxy/debian/rules
Add extra pip options "--ignore-installed", "--no-deps", and "--no-cache-dir" to the dh-virtualenv override in rules files for securedrop-client, securedrop-export, and securedrop-proxy. This prevents variation in the build environment from changing the set of requirements included in the virtualenv embedded in the package.
Fixes #111.
=> Improve dh-virtualenv for securedrop-client

securedrop-client/debian/changelog-buster, securedrop-client/debian/securedrop-client.install, securedrop-workstation-svs-disp/debian/control
Excluding svs-disp package name for now
Blocked on freedomofpress/securedrop-workstation#407
=> VM rename per https://github.com/freedomofpress/securedrop-workstation/issues/285

.circleci/config.yml
We were already building the package on PR runs, but not as nightlies.
Adds a nightly job to changes propagate to the dev lfs repo.
Identified in https://github.com/freedomofpress/securedrop-workstation/issues/282#issuecomment-577461715
=> Builds nightly debs for sd-svs-disp package

.circleci/config.yml
This will speed up the nightly cron job and reduce LFS bandwidth usage.
=> Use shallow clones for securedrop-workstation-dev-rpm-packages-lfs

securedrop-workstation-grsec/debian/changelog-buster, securedrop-workstation-grsec/debian/control, securedrop-workstation-grsec/debian/postinst
Reusing the same config, updating to current stable in advance of SDW
pilot release.
=> Bump kernel image version to 4.14.169

securedrop-log/debian/changelog-buster, securedrop-log/debian/control, securedrop-log/debian/rules, securedrop-log/debian/securedrop-log.install, securedrop-log/debian/securedrop-log.links
This will not pass till get https://github.com/freedomofpress/securedrop-log/pull/8 and https://github.com/freedomofpress/securedrop-debian-packaging/pull/132 merged.
```
$ PKG_VERSION=0.0.4 PKG_DIR=/home/user/code/securedrop-log/dist/securedrop-log-0.0.4.tar.gz make securedrop-log
```
=> Adds changes for updated securedrop-log package

.circleci/config.yml
Now the upstream circleci Python image is coming with the latest
virtualenv, which is causing our builds to fail. This PR removes
the installation done via pip.
It also has YAML formatting fix for another job, and a comment set.
Done via YAML linter/formatter.
All Debian package builds in CI should be green.
After this PR is merged, any open PR on this repo should be rebased.
=> Fixes #141 removes upstream virtualenv from image

securedrop-log/debian/changelog-buster
Includes new logic to read "hostname" from the client VM sending the
logs, to reduce the configuration burden required to run the service.
Refs https://github.com/freedomofpress/securedrop-log/pull/16
See full test plan in the SDW repo, and follow the steps there. Order of operations:
=> Updates securedrop-log to 0.1.1

scripts/update-changelog, securedrop-export/debian/changelog-buster, securedrop-workstation-svs-disp/debian/changelog-buster, securedrop-workstation-svs-disp/mimeapps.list
Towards https://github.com/freedomofpress/securedrop-client/issues/961
* Update mimeapps.list for securedrop-export and securedrop-workstation-svs-disp
* Update securedrop-export to 0.2.2
* Update to securedrop-workstation-svs-disp 0.2.2
see https://github.com/freedomofpress/securedrop-workstation/pull/501
=> securedrop-workstation-svs-disp and securedrop-export 0.2.2

scripts/build-debianpackage, securedrop-export/debian/changelog-buster, securedrop-export/debian/control
Towards freedomofpress/securedrop-workstation#511
Should be reviewed as part of https://github.com/freedomofpress/securedrop-workstation/pull/515, test plan in https://github.com/freedomofpress/securedrop-workstation/pull/515
=> Adds gnome-disk-utility to dependencies of securedrop-export package

README.md
Detail version update step for a subproject. Specifically, we want to ensure the debian changelog is master has an associated tag in the project repository. If the version in debian changelog is greater than that of the one in the project repository, the nightly build will fail (and any failure is cascading, since builds are sequential)
=> Update RM instructions

securedrop-log/debian/rules
Now that securedrop-log does have requirements, adding these two options that we are using for the other packages in this repository, see commit message for more details
=> securedrop-log build: add `--ignore-installed` and `--no-deps`

.circleci/config.yml
Temporarily stopping our dom0 rpm nightly build to enable upload of release candidate rpms to the test repo
=> ci: disable dom0 rpm nightly build to enable pre-release QA

securedrop-client/debian/rules, securedrop-export/debian/rules, securedrop-log/debian/rules, securedrop-proxy/debian/rules
When `pyproject.toml` is added to projects (to support black and isort), pip changes its build processing, requiring downloads of isolated copies of `setuptools` and `wheel`. To avoid having to maintain those in our PyPI index, we can tell pip to not switch to PEP 517 mode.
- Check out the `no-use-pep517` branch in this repo.
- Switch your `securedrop-client` repo to the `add-black-isort` branch, run `python setup.py sdist` for it, then rebuild the Debian package for it. It should complete without error.
=> Prevent use of pip's PEP 517 build process

.circleci/config.yml
After the tarball and wheels are generated, the deb package build
process should thereafter be reproducible. This PR adds a CI check for `securedrop-log`, `securedrop-client`, `securedrop-export`, `securedrop-proxy` to verify that is indeed the case (this was a manual step from https://github.com/freedomofpress/securedrop-workstation/wiki/Workstation-Beta-Acceptance-Tests#packages). 
I'm putting it in a job in CI as the hashes of the built deb are now printed in the CI build output and they should match the deployed packages. This can be used to cross-check with the build logs in the future (indeed, we could adapt this job to run in the LFS repo we use to commit built debs to check the built deb matches the hash of the package built in CI but I'm leaving that for another day).
=> ci: check that deb build process is reproducible after wheels and tarball are generated

securedrop-workstation-grsec/debian/changelog-buster, securedrop-workstation-grsec/debian/control, securedrop-workstation-grsec/debian/postinst
Updates securedrop-workstation-grsec metapackage version to 4.14.186 and updates dependencies to the appropriate kernel and header packages.
=> Bumped workstation kernel metapackage version to 4.14.186

securedrop-workstation-grsec/debian/changelog-buster, securedrop-workstation-grsec/debian/postinst
Prior to building the kernel modules via dkms, let's make sure that paxctld is up and running, and all flags have been applied. Otherwise, a lack of exempting flag could cause the module build to fail.
Related to https://github.com/freedomofpress/securedrop-workstation/issues/590
=> Tweak paxctld logic in kernel metapackage

scripts/build-debianpackage, scripts/update-requirements, scripts/verify-hashes, securedrop-client/debian/rules
Support building packages for projects that use a requirements directory
1. Checkout `move-req-files` client branch (see https://github.com/freedomofpress/securedrop-client/pull/1128)
=> support building projects with a requirments dir

scripts/build-debianpackage
Ready for review. For reference, see discussion in https://github.com/freedomofpress/securedrop-debian-packaging/issues/182#issuecomment-664709727
Full backwards compatibility is retained, so the original invocation will work just fine:
```
PKG_VERSION=0.2.1 PKG_PATH=tarballs/securedrop-client-0.2.1.tar.gz make securedrop-client
```
There's now an optional, terser step to build a package, where the version defaults to the latest tag, and the tarball is generated dynamically from that tag:
```
make securedrop-client
```
Regardless of which method is used, the `.deb` file generated from it is byte-for-byte identical over multiple runs. In both cases, the timestamp information is pulled in from the package changelog. Ideally we'd be using SOURCE_DATE_EPOCH in all places to manage the …
=> Builds source tarballs dynamically

securedrop-workstation-grsec/debian/changelog-buster, securedrop-workstation-grsec/debian/postinst
The u2mfn kernel module is required for GUI operations in a VM. It should be built automatically via dkms, but that process can fail. We must report such errors up to the parent apt operation to notify users. The /etc/kernel/postinst.d/dkms hooks are run on installation of the linux-image-* packages, so we don't need an explicit call to dkms autoinstall (which fails silently) in the metapackage postinst.
Since we've observed VMs fail to build the u2mfn.ko dynamically in the past, let's try to recover in that situation, otherwise fail loudly.
Related issues:
* Closes https://github.com/freedomofpress/securedrop-debian-packaging/issues/184
* Closes https://github.com/freedomofpress/securedrop-workstation/issues/590
In order to verify that changes here reliably resolve the garbled terminal …
=> Checks for u2mfn kernel module in metapackage

README.md
In particular, `apt-test-qubes.freedom.press` is no longer used.
Also clarifies which repo the release tag is pushed to.
=> Update README intro per current state

securedrop-client/debian/postinst
Packaging changes required for https://github.com/freedomofpress/securedrop-client/pull/1159/
Note that `aa-enforce` (and the postinst) command will fail on a kernel that doesn't have AppArmor support, which is the case with Qubes PVH kernels. We could guard against this through a conditional, if we plan on installing the client in other VMs (which sounds unlikely)
See TBD for testplan
=> Enforce AppArmor profile in postinst for securedrop-client

securedrop-client/debian/securedrop-client.install
Follow up to #198. Omitted in the final version for review.
=> Removes mimetypes from securedrop-client package

.circleci/config.yml
This will allow us to publish an RC without it getting clobbered by new commits into the `main` branch, so development of new features can continue while QA is underway.
Ready for review
=> Temporarily disable SecureDrop Client nightlies during pre-release QA

securedrop-client/debian/changelog-buster, securedrop-export/debian/changelog-buster, securedrop-log/debian/changelog-buster, securedrop-proxy/debian/changelog-buster
Updates changelogs for non-metapackage packages required for 0.5.0 securedrop-workstation release.
=> Updated buster changelogs for securedrop-client, -export, -log, -proxy

scripts/generate-tag-message
When tagging the "securedrop-debian-packaging" repository, we include
a list of all package versions, to make reasoning about releases easier
down the road. Collecting this information manually is error-prone, so
let's provide a routine method of generating that info so it can easily
be pasted into a prompt for an annotated git tag, consistent with docs.
=> Adds script to generate tag message

.circleci/config.yml
This reverts commit 3a9a3ffb9fea813652f126684e642f5398a02e43.
Now that https://github.com/freedomofpress/securedrop-client/pull/1188 is merged and 0.3.0 is released, we should re-enable client nighly builds
=> Revert "Temporarily disable nightlies during pre-release QA"

securedrop-workstation-grsec/debian/changelog-buster, securedrop-workstation-grsec/debian/control, securedrop-workstation-grsec/debian/postinst
Tracking upstream changes so that clean installs continue to work.
Attempts to resolve https://github.com/freedomofpress/securedrop-workstation/issues/644
=> Bumps u2mfn version 4.0.30 -> 4.0.31

securedrop-client/debian/changelog-buster
Updates buster changelog for `securedrop-client` package, refs https://github.com/freedomofpress/securedrop-client/issues/1189 . 
I'd previously included a signed tarball, following the documentation in the README. Build logs for that tarball can be found here: https://github.com/freedomofpress/build-logs/commit/1af4af92bbd1d975a5897140066f88cca06c2511 However, the CI checks were [failing the reproducibility tests](https://app.circleci.com/pipelines/github/freedomofpress/securedrop-debian-packaging/794/workflows/fc8d5a82-125c-4897-81a7-3ec669110113/jobs/6176). Since we have fully reproducible deb packages based on signed tags, I'm going to proceed with building from the 0.4.0 tag.
=> Adds changelog for securedrop-client 0.4.0

.circleci/config.yml, .gitignore, Makefile, scripts/build-sync-wheels, scripts/install-deps, tests/test_reproducible_wheels.py
Refs #196
Makes two changes to our existing wheel build process:
1. Setting SOURCE_DATE_EPOCH env var
2. Setting a hardcoded dir path for all wheels builds
With those changes, the `./scripts/build-sync-wheels` script builds wheels that are byte-for-byte reproducible. I also included a test-only Makefile target that was handy during development. It's not yet ready for CI, because I'm seeing the platform vary in the reprotest build environment. More input appreciated if anyone can resolve that problem, see initial report in https://github.com/freedomofpress/securedrop-debian-packaging/issues/196#issuecomment-733417904
First, it's helpful to observe the wheel checksums changing over multiple builds, to understand the problem we're trying to solve.
1. Check out a new branch, _based on main_, …
=> Makes wheel builds reproducible, with tests

.circleci/config.yml
Fixes #216 
See https://app.circleci.com/pipelines/github/freedomofpress/securedrop-debian-packaging?branch=please-build-nightlies for successful build using this commit
=> Update path to copy workstation debs for nightly builds

securedrop-workstation-config/debian/changelog-buster
When running `./scripts/generate-tag-message`, warnings were emitted
about a badly formatted header line:
dpkg-parsechangelog: warning: securedrop-workstation-config/debian/changelog-buster(l5): badly formatted heading line
LINE: -- SecureDrop Team <securedrop@freedom.press>  Tue, 02 Mar 2021 15:00:00 -0400
dpkg-parsechangelog: warning: securedrop-workstation-config/debian/changelog-buster(l7): found start of entry where expected more change data or trailer
LINE: securedrop-workstation-config (0.1.5+buster) unstable; urgency=medium
dpkg-parsechangelog: warning: securedrop-workstation-config/debian/changelog-buster(l7): found end of file where expected more change data or trailer
=> Fixes typo in config 0.1.6 changelog

.circleci/config.yml
To catch syntax errors like the one fixed in #221, this PR adds the existing `lint-deskop-files` Makefile target to CI. I've opted to combine it with the test job for now, since the `install-deps` step is pretty heavy and it's only this one linter for now; would suggest we reorganize if/when we add more linters.
Ready for review
=> Add .desktop file linting to CI

securedrop-workstation-config/mimeapps.list.sd-viewer
M4A files use a different MIME type than MP3 and therefore currently will just silently exit out.
Resolves https://github.com/freedomofpress/securedrop-workstation/issues/664
1. Download https://filesamples.com/samples/audio/m4a/sample1.m4a and upload to your SD instance
2. Sync with SD Client on Qubes and attempt to play
3. [x] Observe failure
4. Build package from this branch & install in `sd-large-buster-template`; shut down template
5. Repeat step 2
6. [x] ~Profit!!!1~ Observe that M4A file now plays as expected
7. Review https://github.com/freedomofpress/securedrop-workstation/pull/665 for updated test
=> Add m4a (audio/mp4) to allow-list for sd-viewer

securedrop-client/debian/changelog-buster
Updates buster changelog for `securedrop-client` package, refs https://github.com/freedomofpress/securedrop-client/issues/1221 so that @emkll can create a tag and sign it in the client repo.
=> add changelog for securedrop-client 0.4.1

securedrop-export/debian/changelog-buster
Updates buster changelog for `securedrop-export` package, refs https://github.com/freedomofpress/securedrop-client/issues/1221 so that @emkll can create a tag and sign it in the export repo.
=> add changelog for securedrop-export 0.2.5

scripts/build-debianpackage
Since we use "set -u" inside the build script, we must test for
definedness of the PKG_GITREF variable. Let's set that to an empty
string by default, which satisfies "set -u".
Closes #228.
=> Fix builds from prod tags

.circleci/config.yml
=> Adds nightly builds for securedrop-workstation-config metapackage

securedrop-client/debian/rules, securedrop-export/debian/rules, securedrop-log/debian/rules, securedrop-proxy/debian/rules, tests/test_reproducible_debian_packages.py
In #231 we noticed that the filesystem path used to build the debian
packages was breaking reproducibility. That's due to the filepath being
recorded inside `direct_url.json`, as stipulated by PEP610.
Also relevant is PEP427, which describes the `RECORD` file for wheels.
Here we remove that file, as well, to ensure full reproducibility
regardless of path.
To evaluate change in the problematic behavior reported in #231, clone this branch fresh in a few different locations, e.g. in DispVMs, and try rebuilding. Make sure that the absolute path of the repo is different between builds! The checksum of the .deb packages should be identical.
=> Adds build_path checks for deb pkg reprotest

.circleci/config.yml, tests/test_reproducible_wheels.py
We were already checking that building a wheel twice yields the same
checksum both times, but we weren't confirming that the checksum matched
what's already committed to version control. Let's do that.
Still leaving the 'reprotest' check enabled because it supports multiple
methods for checking reproducible, which should help us shake out
problems like #231.
Closes #241. 
1. CI must be passing
2. Run `pytest -k test_wheel_builds_match_version_control tests` locally and confirm passing
3. Run `echo this-is-not-a-wheel > localwheels/MarkupSafe-1.1.1-cp37-cp37m-linux_x86_64.whl && gc -m 'TEMPORARY: broken wheel' localwheels/`, then re-run step 2, and confirm the test fails. 
Step 3 ensures that if a wheel build emits a different checksum from what's already version controlled, CI will fail …
=> Tests wheel reproducibility against version control

.circleci/config.yml, .gitignore, dockerfiles/Dockerfile, dockerfiles/Makefile, dockerfiles/image_hash, dockerfiles/push.sh, scripts/install-deps
This PR adds a new container and also uses it in the CircleCI
to test reproducible wheels and Debian packages. The container
is based on standard Debian Buster, thus having the same version
of Python and environment.
closes https://github.com/freedomofpress/securedrop-debian-packaging/issues/253
=> Fixes #253 adds reproducible testing container

securedrop-workstation-grsec/debian/changelog-buster, securedrop-workstation-grsec/debian/postinst
Includes a u2mfn version update, as well, which is required until Qubes
4.1 is final, when we can drop the u2mfn dependency entirely.
=> Bumps workstation kernel to 4.14.240

securedrop-workstation-grsec/debian/changelog-buster, securedrop-workstation-grsec/debian/control, securedrop-workstation-grsec/debian/postinst
The previous version, based on 4.14.240, did not work well in Qubes VMs.
After adjusting the config, rebuilt on an incidentally slightly newer
kernel version, and that artifact behaves well in VMs. Removing the 240
version from the changelog, since it was never shipped to prod.
Also updates the control file fields, which update was omitted in #255.
=> Bumps workstation kernel to 4.14.241

scripts/build-debianpackage
See key rotation blog post for more information:
https://securedrop.org/news/why-we-are-rotating-the-securedrop-release-key/
=> Update signing key fingerprint

securedrop-proxy/debian/rules
Recent nightlies of `securedrop-proxy` were broken, due to missing
imports [0]. In a recent PR [1], the requirements files within the
securedrop-proxy repo (and therefore tarball) were moved, and the
package build logic depends on those locations.
To my great surprise and disappoint, dh_virtualenv evidently will not
complain if a `--requirements` file does not exist. The build will be
called successful. That's unacceptable, so I've modified the
debian/rules file to test for existence as a workaround. If folks agree
this is a sane solution, we should update the rules files for the other
packages to match.
[0] https://github.com/freedomofpress/securedrop-proxy/issues/94
[1] https://github.com/freedomofpress/securedrop-proxy/pull/92
To test, you can manually build a package with this change …
=> Update proxy reqs path

.circleci/config.yml, securedrop-client/debian/rules, securedrop-export/debian/rules, securedrop-log/debian/rules
Just like we did here: https://github.com/freedomofpress/securedrop-debian-packaging/pull/266 use the latest path for the build requirements file
=> update paths for build reqs for various projects

scripts/build-debianpackage
The upstream raw html on GitHub release pages has changed, and doesn't
include the tag info we want. That's fine: we'll just query tags
directly. The function fix here is the "releases" -> "tags" change in
the curl call; the rest of the diff is the result of running shellcheck
against the script and addressing the problems reported.
Closes #277.
=> Fix inferring version in build pkg script

securedrop-client/debian/changelog-buster
Hotfix release to resolve a broken build for 0.5.0.
Bumping version in order for clarity about communicating versions.
=> Bump securedrop-client to 0.5.1

.circleci/config.yml
Pause SDW nightlies so that we don't clobber environments during QA of `securedrop-client 0.6.0`. See release tracking issue: https://github.com/freedomofpress/securedrop-client/issues/1402 (there is a step to unpause nightlies so that we don't forget to undo this)
=> pause all nightlies for securedrop-client 0.6.0 QA

securedrop-client/debian/changelog-buster
Bumping version, in line with https://github.com/freedomofpress/securedrop-client/pull/1421. Should be reviewed together.
=> securedrop-client 0.6.0-rc3

securedrop-client/debian/changelog-buster
Bump version of `securedrop-client` package to 0.6.0, preparing for final release. Refs https://github.com/freedomofpress/securedrop-client/issues/1402. Should be reviewed in tandem with https://github.com/freedomofpress/securedrop-client/pull/1425
=> Bump changelog for securedrop-client 0.6.0

scripts/update-changelog, securedrop-client/debian/changelog-buster
We're not final on 0.6.0 just yet. Create another rc.
Related to https://github.com/freedomofpress/securedrop-client/pull/1427
=> securedrop-client 0.6.0-rc4

securedrop-client/debian/changelog-buster
The second attempt at releasing 0.6.0 final. Adjusting the version after rc4.
See also https://github.com/freedomofpress/securedrop-client/pull/1428
=> Bumps version for securedrop-client to 0.6.0

.circleci/config.yml
This reverts commit e4cbdbb16c226124af7f2b7221b25a90821994d9, to unpause SDW nightlies, see https://github.com/freedomofpress/securedrop-debian-packaging/pull/286 for more info.
=> Revert "pause all nightlies for securedrop-client 0.6.0 QA"

.circleci/config.yml
Ready for review
Instead of maintaining and running a custom molecule playbook to pull
down Tor packages, we can use reprepro's built-in update functionality.
Once <https://github.com/freedomofpress/securedrop-dev-packages-lfs/pull/128>
is merged, we can run `reprepro update` to automatically check the
upstream Tor apt repo, pulling down new debs if they're available.
The CI job checks out the securedrop-dev-packages-lfs repository, runs
`reprepro update` and copies over the newly fetched debs. If there's a
difference, it'll commit the new packages and push.
In the future we could publish an image with the reprepro, etc. packages
pre-installed so we don't have to do it at runtime.
Refs <https://github.com/freedomofpress/securedrop/issues/6233>.
* Step through the commands manually inside …
=> Have CI automatically update Tor packages in apt-test

.circleci/config.yml
The job is currently failing with:
> Cloning into 'securedrop-dev-packages-lfs'...
> The authenticity of host 'github.com (140.82.114.3)' can't be established.
> ECDSA key fingerprint is SHA256:p2QAMXNIC1TJYWeIOttrVc98/R1BUFWu3/LiyKgUfQM.
> Are you sure you want to continue connecting (yes/no/[fingerprint])?
It's unclear to me how the other nightly jobs are getting the correct
fingerprint but this should do it for this job.
=> Preload github.com SSH fingerprint in reprepro-update-tor CI job

securedrop-client/debian/changelog-buster
Update changelog for securedrop-client 0.7.0-rc2.
Towards https://github.com/freedomofpress/securedrop-client/issues/1465
=> Update changelog for securedrop-client0 0.7.0-rc2

.circleci/config.yml
Once <https://github.com/freedomofpress/securedrop-dev-packages-lfs/pull/145>
lands, our reprepro script will treat the new `workstation/buster-nightlies`
directory as going to a separate nightlies component, which keeps main
clear for manually uploaded release candidates.
Fixes #289.
=> Publish workstation nightlies in a separate nighly component

securedrop-client/debian/changelog-buster
Update changelog for securedrop-client 0.7.0-rc3
Towards https://github.com/freedomofpress/securedrop-client/issues/1465
=> update changelog for securedrop-client 0.7.0-rc3

securedrop-client/debian/changelog-buster
Update changelog for securedrop-client 0.7.0
Towards https://github.com/freedomofpress/securedrop-client/issues/1465
=> Update changelog for securedrop-client 0.7.0

tests/test_reproducible_debian_packages.py
When reprotest fails, leave the environment behind for easier
interactive debugging of specific commands that failed. In CI everything
is thrown away anyways, so this should only affect people locally
running reprotest.
Refs #298.
=> Pass --no-clean-on-error to reprotest for easier debugging

.circleci/config.yml, scripts/clean-old-nightlies.py
Have CI run a quick Python script that will delete workstation nightlies
after 2 weeks to keep the repository size down.
This job requires the previous nightly builds to succeed, so if the
nightlies break for whatever reason, deletion will also be paused.
=> Have CI delete nightlies older than 2 weeks

.circleci/config.yml
The job was failing with:
> /bin/bash: line 14: ./scripts/clean-old-nightlies.py: No such file or directory
I was missing the special "checkout" job that clones the current git
repo and puts it in the working directory, see
<https://circleci.com/docs/2.0/configuration-reference/#checkout>.
=> Add missing "checkout" step for clean-old-nightlies job

securedrop-workstation-config/debian/changelog-buster
Towards https://github.com/freedomofpress/securedrop-debian-packaging/issues/312
Once this is merged, we can tag `securedrop-debian-packaging` and build a new `securedrop-workstation-config` debian package an push to `securedrop-dev-pacakges-lfs`.
=> update changelog for securedrop-workstation-config 0.1.7

.circleci/config.yml, scripts/build-debianpackage
The end goal is that each repository has all the necessary files to
build a Debian package, without needing this repository. This gets us
partially there for metadata in the debian/ directory.
Currently we build a sdist tarball and use it as the source tree for
packaging. This has some nice properties in that we can exclude some
unnecessary files and lets us control timestamps for reproducibility.
This comes at a higher cognitive cost of needing to know everything that
ends up in a sdist tarball and complexity to reset timestamps.
With this change, we now use the Git repo tree as the source tree for
packaging. Steps like copying over a debian/ directory from this
repository and installing a platform-specific changelog are guarded on
files existing so they can be removed/adjusted on a …
=> Build native packages with debian/ in source tree

.circleci/config.yml, scripts/install-deps
This will dramatically shrink the number of dependencies needed when
running `install-deps` from 4GB to 200MB because all of the diffoscope
dependencies aren't needed.
We only need reprotest for three different CI pipelines, so manually install
it there instead of everywhere.
Fixes #318.
----
Without this change:
With this change:
So we're looking at a ~2min speed up for the main build jobs, which should be a noticable speedup on the various component repositories. And spinning up a new container locally will no longer have to download 4G worth of packages...
=> Only install reprotest when needed

scripts/build-debianpackage, scripts/install-deps
First, explicitly install python3-virtualenv
The version of dh_virtualenv on bullseye allows using `python3-venv` and
if present, won't install `python3-virtualenv`. Since we still need
virtualenv, install it explicitly for now until we can transition to
using venv.
Second, automatically determine platform being built for
Instead of requiring `PKG_PLATFORM` to manually be set, we can get the
current platform from `/etc/os-release`.
The build script will also now adjust the platform in the version
number, so we don't need to maintain separate changelogs that are
identical except for version.
Refs #321.
=> More bullseye fixes

.circleci/config.yml
* Hardcode `changelog-buster` since we're not ready to rename it to
a generic `changelog` yet, but we want to enable bullseye builds.
* Add job for building securedrop-keyring on bullseye
* Add buster+bullseye nightlies for the keyring to continually ensure
the package is buildable even though it rarely changes.
* Ensure the nightly directory exists with `mkdir -p` since the bullseye
one doesn't exist yet.
=> Test securedrop-keyring on bullseye and add nightlies

.circleci/config.yml
Towards https://github.com/freedomofpress/securedrop-debian-packaging/issues/321
As it says on the tin (thanks to @creviera [for flagging](https://github.com/freedomofpress/securedrop-debian-packaging/pull/325/files#r881086513))
=> Fix template for `securedrop-log` nightly builds

scripts/build-debianpackage
There's a subtle bug in which we (read: I) incorrectly assumed that
PKG_PATH will always end in PKG_NAME, so copying it over into
$TOP_BUILDDIR will create the appropriately named subdirectory and
everything is happy.
This assumption is wrong in all the component repository CI pipelines,
where the path points to a directory named "project". Adjust the `cp`
command with the magic `-T` flag to stick the files in the correctly
named directory that we expect later on.
Thanks to Gonzalo for helping with debugging.
=> Fix building packages when PKG_PATH doesn't end in PKG_NAME

securedrop-client/debian/control, securedrop-export/debian/control, securedrop-keyring/debian/control, securedrop-log/debian/control, securedrop-proxy/debian/control, securedrop-proxy/debian/rules, securedrop-workstation-config/debian/control, securedrop-workstation-grsec/debian/control, securedrop-workstation-svs-disp/debian/control, securedrop-workstation-viewer/debian/control
Fixes https://github.com/freedomofpress/securedrop-debian-packaging/issues/333
When we bumped the debhelper compat level from 9 to 12, buster and bullseye packages could no longer be built in CI by pointing the builder at a source tarball that was generated by running: `python3 setup.py sdist`. 
We still want to bump the compat version up from 9 to 11 (we only remove `setuptools` in the rules file with this version bump because it's no longer needed). But too much is broken when we bump to 12, so I created an issue to capture the work involved in order to do that bump (https://github.com/freedomofpress/securedrop-debian-packaging/issues/335).
=> set debhelper compat to 11 for all projects

.circleci/config.yml
We were updating d/changelog-buster when we needed to update d/changelog-bullseye.
=> Fix nightly bullseye grsec package build

securedrop-export/debian/control
* Depends on freedomofpress/securedrop-dev-packages-lfs#161
Closes #343 by:
1. removing the `Depends` specification for `task-print-server`, which is no longer available in bullseye;
2. retaining the `Depends` specifications for `cups` and `system-config-printer`; and
3. retaining the `Depends` specification for `xpp`, which we host for bullseye after freedomofpress/securedrop-dev-packages-lfs#161.
=> build(securedrop-export): reconcile dependencies uninstallable in bullseye

securedrop-export/debian/control
Previously (on buster) `task-print-server` would automatically install all printer drivers as it listed `printer-driver-all` as a recommended package. But it was removed as a dependency because it doesn't exist in bullseye anymore, so we want to explicitly depend on the printer drivers we need for this package.
Fixes #346
=> `securedrop-export`: Add printer driver dependencies

.circleci/config.yml
Now that we're assuming Python 3.9 under Debian bullseye, that's the
environment we should use for testing wheel-level reproducibility.
Closes #350.
=> ci(reprotest-wheels): switch to Debian bullseye

.circleci/config.yml
The package is broken and we really don't need nightlies for
kernel things, because the kernel is special.
Fixes https://github.com/freedomofpress/securedrop-workstation/issues/793.
=> Stop building securedrop-workstation-grsec package in nightlies

securedrop-workstation-viewer/debian/changelog-bullseye
Towards https://github.com/freedomofpress/securedrop-debian-packages-lfs/issues/84
=> Add securedrop-workstation-viewer-0.2.0 (bullseye) changelog entry

securedrop-export/debian/changelog-bullseye
Towards https://github.com/freedomofpress/securedrop-export/issues/98
Towards https://github.com/freedomofpress/securedrop-debian-packages-lfs/issues/84
=> Add (bullseye) changelog for securedrop-export-0.3.0

securedrop-client/debian/changelog-buster
See https://github.com/freedomofpress/securedrop-client/blob/0.8.0/changelog.md
=> Add Bullseye change log entry for SecureDrop Client 0.8.0

README.md
The script requires a PKG_VERSION as well:
https://github.com/freedomofpress/securedrop-debian-packaging/blob/adf54b816c87fe53f551853d98d6056b1c107486/scripts/update-changelog#L32-L35
=> docs: README correction for changelog script invocation

securedrop-client/debian/changelog-buster, securedrop-export/debian/changelog-bullseye, securedrop-export/debian/changelog-buster, securedrop-log/debian/changelog-bullseye, securedrop-log/debian/changelog-buster, securedrop-proxy/debian/changelog-bullseye, securedrop-proxy/debian/changelog-buster, securedrop-workstation-viewer/debian/changelog-bullseye, securedrop-workstation-viewer/debian/changelog-buster
Closes #362 by merging `changelog-bullseye` entries into `changelog-buster`, so that all non-kernel (`securedrop-workstationg-grsec`) nightly jobs jobs read and update a single changelog file.
Per <https://github.com/freedomofpress/securedrop-debian-packaging/issues/362#issuecomment-1190784465>, `changelog-buster` will eventually become the canonical `changelog` file.
=> chore: merge bullseye changelogs into "buster" changelog

securedrop-keyring/debian/preinst
Updates the key removal code in the `preinst` check in the `securedrop-keyring` package.
This `preinst` check removes any redundant copies of the key from `/etc/apt/trusted.gpg` (they keyring package itself places the key in `/etc/apt/trusted.gpg.d/`). However, because it is looking for an outdated fingerprint, it won't find it even if it exists.
Resolves #367 
On a machine that is configured as `prod`, or that was re-provisioned from `prod` to `dev` without an uninstall in between, you should be able to find evidence that the production signing public key exists in `/etc/apt/trusted.gpg`, by running the following commands in `sd-app`:
```bash
mkdir /tmp/tempkey
gpg --homedir="/tmp/tempkey" --no-default-keyring --keyring /etc/apt/trusted.gpg --list-keys
```
It's expected to find the …
=> Update release key fingerprint in securedrop-keyring preinst check

.circleci/config.yml
Instead of having each nightly job push to the apt-test repo, they now
store the resulting .deb in a CircleCI workspace[1], which the final
"push-packages" job will copy from and commit.
This provides a number of benefits, including:
* faster nightlies since builds are parallelized
* no maintaining a complex "requires" list of jobs
* build jobs don't have access to SSH key for apt-test
* only two commits instead of 10-12
It also unlocks future improvements, such as:
* consolidating the build- and build-nightly jobs for DRY
* folding cleanup-nightlies script into the same push operation
Finally I expect this (and future DRY work) to make it easier to add
bookworm support in the near future.
[1] https://circleci.com/docs/workspaces
The …
=> Parallelize nightly builds

.circleci/config.yml
* Parameterize nearly all the jobs by package name and distro
* Get rid of all unused common-steps stanzas
* Merge regular and nightly jobs together by conditionally
determining whether we're supposed to build nightlies or not
* workstation-grsec package left as-is for the most part, it's
going to be removed from here soon, once <https://github.com/freedomofpress/kernel-builder/pull/24> is merged.
<https://circleci.com/blog/circleci-matrix-jobs/> is a good overview
of the CircleCI features used in this PR.
----
The main motivation for this is that it's now a 4 line PR to add bookworm support!
=> Use matrix parameterization to reduce duplication in CI config

.github/PULL_REQUEST_TEMPLATE/changelog_update.md, .github/PULL_REQUEST_TEMPLATE/default.md, .github/PULL_REQUEST_TEMPLATE/package_addition.md, PULL_REQUEST_TEMPLATE.md
This is primarily aimed at preventing us from missing any dependency review in the future.
1. Adds an item to remind that diff reviews must be performed when adding packages
2. Adds a template for change log updates, which are relatively frequent
3. Moves the default template, and rewords it slightly to match the other
Prompted by: #379
=> Add pull request templates for common tasks

tests/test_reproducible_wheels.py
Accidentally missed. Also fix a typo in a comment while we're at it.
=> Test securedrop-export wheels are reproducible too

.gitignore, scripts/build-sync-wheels, scripts/update-requirements, scripts/utils.py, tests/test_update_requirements.py
* Make sure we call `os.path.expanduser()` on `pkg_dir`
* Try to guess project from `setup.py` instead of expecting it to be cloned in a specific way (that breaks in CI).
Closes https://github.com/freedomofpress/securedrop-client/pull/1572
* Rename your `securedrop-client` folder to something else, I did `securedrop-test`.
* from this repo, run `PKG_DIR=~/github/freedomofpress/securedrop-test make requirements`, with a tilde specifically, and make sure it works properly.
=> Fix a few breaking changes in scripts

scripts/build-sync-wheels
Otherwise you get a super obscure error about `build.__main__` being a package that can't be directly executed.
Fixes #388.
In a container/VM, run `make install-deps` and don't activate the venv. Make sure you're a non-root user.
=> Have `build-sync-wheels` error if not in a virtualenv

.circleci/config.yml
Because we weren't running `git add` after the cleanup script deleted stuff it wasn't actually getting committed.
Fixes #397.
=> Actually commit the result of clean-old-nightlies

securedrop-client/debian/securedrop-client.install
This is  follow up on https://github.com/freedomofpress/securedrop-client/pull/1589 and https://github.com/freedomofpress/securedrop-client/pull/1600, that ensures that the file name that's referred to by the SecureDrop Client application is the one that's installed when installing the application.
:crystal_ball: **Reviewers**: the CI pipeline will need to be triggered again after https://github.com/freedomofpress/securedrop-client/pull/1600 is merged. Failures are expected before that.
=> Rename desktop entry after freedesktop specifications

.circleci/config.yml, scripts/new-tor-issue
CI will now create a new issue (or update an existing one) whenever it fetches new Tor packages. This is something that I have been doing manually for a while now whenever I see a new Tor release announcement.
The generated issue contains the checklist as well as the diff of the new debs so you can see the version and checksums of the packages. An example issue (with the wrong patch) is
<https://github.com/freedomofpress/securedrop/issues/6723>.
Some potential future improvements that I deferred for now is to include the version number in the issue title, and the correct Tor Project forum link.
The script wraps around the official `gh` CLI tool, it needs a GITHUB_TOKEN to be set in the environment to work properly. `gh` is only available in bullseye-backports, so I had to adjust the image …
=> Create issues when a new Tor release is fetched

.circleci/config.yml
Follow-up to 1862e178a1abb08.
I wrongly understood how bash grouped || and &&. We wanted `diff-index || (commit && push && new-tor-issue)`, but instead bash gave us `(diff-index || commit) && push && new-tor-issue`, which meant that regardless of whether there is a new package, we were pushing (harmless) and running the new-tor-issue script (disruptive!).
By adding explicit parenthesis it should do what we actually want.
=> Only run new-tor-issue when we have a new package (for real)

scripts/promote-suite
The new `./scripts/promote-suite` simplifies the process of promoting packages from the dev repository to the prod one.
The primary use case currently is for promoting Tor and Linux packages.
For each package in the dev repo, it compares the highest version to the highest version in the prod repo, copying over the dev package if they don't match. There are some edge cases where this doesn't work (which is annotated with a code comment), but it should get the majority correct.
As a side-effect, it could reveal when a package in dev was forgotten for promotion to prod.
In the future this script could be fancier by showing debdiffs and diffoscopes of the newly promoted packages, or a dry-run mode that shows which packages are pending promotion.
I've wanted to do this for a while, mostly …
=> Add script to simplify promoting packages from dev to prod

.circleci/config.yml, README.md, scripts/clean-old-packages, scripts/new-tor-issue, scripts/promote-suite
For https://github.com/freedomofpress/securedrop-builder/issues/304, rename references to the renamed repos in CircleCI configs and scripts. See also https://github.com/freedomofpress/securedrop-builder/pull/400, which makes more updates to documentation -- the change here will be removed by one of those commits, but I left it in for clarity.
We will proceed with the renaming on the GitHub end later today (2023-02-14), but old clones will continue to work.
=> Update apt LFS repo names

.circleci/config.yml
The setuptools in bookworm now enforces PEP 440 compliance for version numbers rather than just warning about it.
We can fall into compliance by just removing the extra dashes.
Specifically:
Previous format: 0.4.0-dev-20230214-235645
New format: 0.4.0.dev20230214235645
Fixes #414.
=> Make nightly versions compliant with PEP 440

scripts/install-deps
The fixed dh_virtualenv version is now in Debian Bookworm, so we no longer need to patch it ourselves:
* https://tracker.debian.org/news/1418871/accepted-dh-virtualenv-122-13-source-into-unstable/
* https://tracker.debian.org/news/1420883/dh-virtualenv-122-13-migrated-to-testing/
=> Stop patching dh_virtualenv for Python 3.11+, now fixed

securedrop-client/debian/changelog-buster
- adds securedrop-client 0.9.0-rc1 changelog entry (in legacy changelog-buster file)
=> Added changelog for ssecuredrop-client 0.9.0-rc1

securedrop-client/debian/changelog-buster, securedrop-client/debian/securedrop-client.install
- debian changelog entry for 0.9.0-rc2 added
- `files/securedrop-client.desktop` added back to debian .install file (see securedrop-client#1638)
=> Add build changes for securedrop-client 0.9.0-rc2

.circleci/config.yml
To theoretically try independently reproducing these builds, just like we want to for release builds. This also provides the checksum of packages in a machine-readable format.
We push to build-logs before apt-test to allow eventual CI in apt-test
to verify that packages in that repository match the published buildinfo.
Refs <https://github.com/freedomofpress/securedrop/issues/6356>.
=> Publish buildinfo files to build-logs repository

.circleci/config.yml
In theory it's general but currently expecting the pending securedrop-updater Makefile and folder layout and assume that securedrop-workstation's rpm will be modified to follow this layout too.
Fixes https://github.com/freedomofpress/securedrop-updater/issues/10
=> Have CI build nightlies for securedrop-updater

scripts/check-buildinfo
buildinfo files contain package checksums in a machine-readable format, so script checking newly added packages against those.
This will be added to CI for securedrop-apt-test and securedrop-apt-prod.
The main iffy part of this is how it compares against "origin/main", but I think for PRs it'll mostly do the right thing. We only check new packages because old ones don't have buildinfo published. Maybe once we no longer have any legacy cases left, we just check everything in the repository.
Likely there are more checks that could be added, but this is a start.
Refs <https://github.com/freedomofpress/securedrop/issues/6356>.
=> Add script to check newly added packages against buildinfo files

README.md, scripts/build-debianpackage
Fixes #426 
Removes option to build using PKG_VERSION. Build options are now PKG_PATH and PKG_GITREF:
- when invoked without either PKG_PATH or GITREF set, will error out (previously built last known release)
- when invoked with PKG_PATH, will use the source tree or tarball at `$PKG_PATH` to build package (no checkout, no tag verification)
- when invoked with PKG_GITREF, will check out corresponding gitref attempt release key verification verification if PKG_GITREF looks like a release tag (catching sneaky branches!) and, if all is well, build package 
In all cases the package version will be derived from the latest version in the source tree's `debian/changelog` If a release tag PKG_GITREF is specified and doesn't match the changelog version, the build will not proceed.
=> update build script to remove PKG_VERSION, use only PKG_PATH or PKG_GITREF modes.

securedrop-keyring/debian/changelog-buster, securedrop-proxy/debian/changelog-buster
Refs #437.
Refs <https://github.com/freedomofpress/securedrop-proxy/issues/116>.
=> Bump securedrop-proxy and securedrop-keyring changelogs

Makefile, securedrop-keyring/debian/rules, tests/test_deb_package.py
Closes #450 
- Don't include conffiles for securedrop-keyring 
- Add deb test that tests this behaviour only for securedrop-keyring, and add test to `make tests` target
- In a debian-based vm, install seuredrop-keyring-0.1.7 from apt-test
- Build securedrop-keyring-0.2.0 deb from the tip of this branch, and install it using dpkg
=> Remove Debian autogenerated conffiles from securedrop-keyring

.circleci/config.yml
Closes #456 
Split the actual push operation to a new "push-rpm" job that runs after both the workstation and updater nightlies have been built, following the same pattern for the debs.
Because the "build-rpm" job no longer pushes, we now also run it for each commit to this repository.
=> Build securedrop-workstation RPM nightlies

securedrop-proxy/debian/rules
This should be merged together with https://github.com/freedomofpress/securedrop-proxy/pull/122 and will fail until then.
=> Update build-requirements.txt path for securedrop-proxy package

securedrop-proxy/debian/rules
This can be merged after both #461 and https://github.com/freedomofpress/securedrop-proxy/pull/122 have landed. It's intentionally based off #461 so includes that commit until it is merged.
=> Finalize proxy path

securedrop-client/debian/rules, securedrop-export/debian/rules, securedrop-log/debian/rules
This file will be moving to the repository root in the near future as part of our migration to poetry, making the packaging compatible with both eases the transition.
=> Add backwards-compatible reference to new build-requirements.txt

scripts/update-requirements, scripts/utils.py
poetry doesn't normalize case in package names, so in securedrop-client we have jinja2 depending on "MarkupSafe", but the package itself in the lock file is named "markupsafe".
We can avoid this by changing the relevant_dependencies to all be lowercase when reading them out of pyproject.toml (the "main" dependencies) and when reading from poetry.lock.
=> Fix issues around case-sensitive matching in poetry support

.circleci/config.yml, scripts/clean-old-packages
Ready for review, but needs https://github.com/freedomofpress/securedrop-yum-test/pull/51 to be merged first.
Extend the `clean-old-packages` script so it works for RPMs too. We use the Python RPM bindings to extract package name and version and then shell out to `rpmdev-vercmp` to sort them.
The behavior is now the same as the deb cleanup, when new nightly packages are pushed, it'll clean up old nightlies in the same commit. RC packages (in the `f32` component) will be cleaned up in a separate commit, if necessary.
Fixes #435.
=> Cleanup old RPM nightlies too

.github/dependabot.yml, .github/workflows/ci.yml, Makefile, pyproject.toml, scripts/utils.py, test-requirements.txt, tests/test_deb_package.py, tests/test_reproducible_debian_packages.py, tests/test_reproducible_wheels.py, tests/test_update_requirements.py, tests/test_utils.py
Adds a GitHub action that runs format & lint checks.
Draws from https://github.com/freedomofpress/securedrop/pull/6961 for the ruff config.
I've implemented several of the linter suggestions while ignoring others.
This PR also applies `ruff`'s code formatting (which in turn is a drop-in replacement for `black`). `ruff` appears to be a bit less aggressive than `black` in enforcing line length, so we have to disable the line length check itself.
NB: Our undocumented use of `test-requirements.txt` is another potential candidate for Poetry; I've saved this for a follow-up change.
Fixes #463 
- Visual review
- Review output of new "checks" GitHub actions
- Install `test-requirements.txt` in a venv and verify that Makefile targets work as expected
=> Add ruff for lint & formatting checks; apply some suggested fixes

Makefile, README.md
The main issue is that our previous hack to detect the component name from the folder no longer works, since it'll now be an unprefixed "client", so have the Makefile add the prefixing in.
Documentation has been updated as well.
Fixes #486.
=> Fix building of wheels in monorepo and update docs

pyproject.toml, scripts/utils.py
We're currently installing the latest version of `ruff` in CI without pinning. Until we change that, we'll have to keep up with upstream behavior changes. This PR does that - it updates the configuration format to silence a couple of deprecation warnings, and applies a small formatting change that a previous version did not catch.
=> Update ruff config format; apply latest fix

.github/workflows/ci.yml
Avoids a situation like <https://github.com/freedomofpress/securedrop-builder/pull/497#issuecomment-2073826834>, where wheels are updated, but the sha256sums and associated signatures are not.
=> Verify sha256sums.txt and signatures in CI

scripts/check-buildinfo
Fixes #504 by matching on both Ubuntu-style `.ddeb` and Debian-style `.deb` extensions for `dbgsym` packages, but always use the latter for lookup.
Incidentally adds an `--against $REF` argument and formats with ruff.
Something like:
```sh-session
$ cd ~/securedrop-builder
$ git fetch
$ git checkout 504-ubuntu-dbgsym
$ cd ~/build-logs
$ git pull
$ cd ~/securedrop-apt-test
$ git pull
$ ~/securedrop-builder/scripts/check-buildinfo --against HEAD~2 ~/build-logs/ | grep "dbgsym"
OK: got expected checksum 2d3d6e6e5d551dbe9aa59df2179b41a65a180d986bd5919df0a329a56c238c50 for securedrop-app-code-dbgsym_2.11.0~rc1+focal_amd64.deb
OK: got expected checksum af4ef1de1ed3d3572077cd4a7adf9f82e5cb878676714dba15f7e0517f5bc9e2 for securedrop-config-dbgsym_2.11.0~rc1+focal_amd64.deb
```
=> fix: handle mismatch between a `dbgsym` package's extension and `buildinfo` record

.github/workflows/ci.yml, .github/workflows/reprotest.yml, Makefile, poetry.lock, pyproject.toml
_**Note**: this depends on https://github.com/freedomofpress/securedrop-builder/pull/506, which should be merged first_
We just need to set `persist-credentials: false` in all of our workflows.
Refs <freedomofpress/securedrop-tooling#18>.
=> Lint our GitHub Actions workflows with zizmor
