securedrop-client/debian/securedrop-client.install, securedrop-client/debian/securedrop-client.links
This update is required for alembic based client and all related changes.
=> Adds the install file for the package and removes old links

Makefile
There's no actual build logic yet, simply a scaffold for adding the specific build steps, likely via a separate script.
Related to #6 (but does not resolve).
=> Begins Makefile for codifying packaging steps

securedrop-client/debian/changelog, securedrop-client/debian/securedrop-client.install
changes for building securedrop-client 0.0.3
=> securedrop-client 0.0.3

securedrop-workstation-svs-disp/debian/changelog, securedrop-workstation-svs-disp/paxctld.conf.svsdisp
Will address issues raised in the review of https://github.com/freedomofpress/securedrop-workstation/pull/201
=> Add pax flag for totem

simple/markupsafe/index.html, simple/pytest-random-order/index.html, simple/pytest/index.html, simple/requests/index.html, simple/securedrop-sdk/index.html, simple/sqlalchemy/index.html
New index HTML file updates for the upstream releases.
=> Updates the index files for latest upstream releases

README.md
Resolves #41
Updates the changelog process in the docs.
=> update changelog instructions

.circleci/config.yml
Prevents race condition identified by @redshiftzero in https://github.com/freedomofpress/securedrop-debian-packaging/pull/71/files#r306918085
=> Sequential nightly builds

.circleci/config.yml, Makefile, scripts/update-requirements, test-requirements.txt, tests/test_update_requirements.py
towards #83
it would be nice when we make modifications going forward we also add a test covering that behavior (easier to review, easier to ensure we don't break something in the future)
=> test/ci: add some initial tests for ensuring build fails

securedrop-log/debian/changelog-buster
=> securedrop-log 0.0.2

.circleci/config.yml
in order to review/merge: https://github.com/freedomofpress/securedrop-proxy/pull/55
=> disable stretch securedrop-proxy jobs

.circleci/config.yml
deletes all stretch jobs (per-PR and nightly)
=> ci: disable all stretch jobs (per-PR and nightly)

README.md
Added instructions for adding build logs to the build-log repo and steps for verfying tags, tarballs, and deb packages
=> add build-log and verification steps

README.md
Just a quick update to the docs to reflect how we no longer need to build tarballs manually.
=> update to reflect reproducible builds process

securedrop-export/debian/changelog-buster
=> Add changelog for securedrop-export 0.2.6

README.md
Add docs for how to build a debian package for development and test purposes.
=> Docs for how to skip signature verification

securedrop-client/debian/changelog-buster
After this is merged, immediately tag this packaging repo and checkout the tag to build the client deb.
=> update changelog for securedrop-client 0.5.0 release

securedrop-client/debian/changelog-buster
Add changelog for `securedrop-client  0.6.0-rc1`
=> Add changelog for securedrop-client 0.6.0-rc1

securedrop-client/debian/changelog-buster
Update changelog for 0.7.0-rc1
=> Update changelog for securedrop-client-0.7.0-rc1

.circleci/config.yml
=> Build nightlies for -config and -svs-disp

securedrop-client/debian/changelog-buster
=> Update securedrop-client change log

project.json
This PR silences security alerts for some vulnerabilities, as part of security triage.
Context: https://github.com/freedomofpress/fpf-www-projects/pull/290
=> Security triage

securedrop-client/debian/changelog-buster
- Updates securedrop-client debian changelog.
=> added 0.9.0 securedrop-client changelog entry

.circleci/config.yml, scripts/build-debianpackage, tests/test_reproducible_wheels.py
* _To be merged after https://github.com/freedomofpress/securedrop-client/pull/1675_
=> Update builds for new monorepo structure
